apiVersion: v1
kind: Service
metadata:
  name: wagi-http
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 3000
  selector:
    kubevirt.io/domain: wagi
  type: LoadBalancer